apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: gymin97/msa-dev:mysql5.7_v1
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: frodo5020!!
        - name: MYSQL_DATABASE
          value: boot_board
        - name: MYSQL_USER
          value: frodo
        - name: MYSQL_PASSWORD
          value: frodo5020!!
        - name: MYSQL_ROOT_HOST
          value: '%'
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
