apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: backend # namespace
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 940168446867.dkr.ecr.us-west-1.amazonaws.com/test-gm:mysql-v1
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rlarudals
        - name: MYSQL_DATABASE
          value: django_db
        - name: MYSQL_USER
          value: python
        - name: MYSQL_PASSWORD
          value: python
        - name: MYSQL_ROOT_HOST
          value: mysql-svc
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi