apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: backend
spec:
  type: ExternalName
  externalName: mysql2.cersrmaeghas.us-west-1.rds.amazonaws.com # FQDN
  ports:
  - port: 3306
    targetPort: 3306
