apiVersion: v1
kind: Secret
metadata:
  name:  mysql-pass
  namespace: backend
data:
   rootpass:  cmxhcnVkYWxz #qwer1234 인코딩 된 password
   username:  cHl0aG9u # python
   userpass:  cHl0aG9u # python
type: Opaque
