apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db # pod name (mysql-0, mysql-1 ..)
spec:
  serviceName: "mydb"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: rootpass
              name: db-pass
        - name: MYSQL_DATABASE
          valueFrom: 
            secretKeyRef:
              key: dbname
              name: db-pass
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: db-pass
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: pass
              name: db-pass
        - name: MYSQL_ROOT_HOST
          value: '%'
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: korean
          mountPath: /etc/mysql/conf.d
      volumes:
      - name:  korean
        configMap:
          name: mysql-conf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi