--- 
apiVersion: v1
data: 
  was.conf: |-
      upstream was {
          server was-svc:8080;
      }
      
      server {
          listen 80;
          server_name web-svc;
          access_log /var/log/nginx/access.log;
      
      location / {
      
              #root /usr/share/nginx/html;
              index index.html index.htm index.jsp;
              proxy_pass http://was;
          }
      
          location ~ \.(css|js|jpg|jpeg|gif|htm|html|swf)$ {
              root /usr/share/nginx/html;
              index index.html index.htm;
          }
      
          location ~ \.(jsp|do)$ {
          index index.jsp;
              proxy_pass http://was;
         
          proxy_redirect off;
          charset utf-8;
          }
      
          error_page 500 502 503 504 /50x.html;
          location = /50x.html {
              root /usr/share/nginx/html;
          }
      }
kind: ConfigMap
metadata: 
  name: nginx-conf
