apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name:  log
            mountPath: /var/log/nginx
          - name: conf
            mountPath: /etc/nginx/conf.d
        ports:
          - containerPort: 80
      volumes:
        - name: log 
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: conf
          configMap:
            name: nginx-conf
