apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gymin97/msa2:nginx_v1
        volumeMounts:
          - name:  log
            mountPath: /var/log/nginx
          - name: conf
            mountPath: /etc/nginx/conf.d
        ports:
          - containerPort: 80
      volumes:
        - name: log 
          nfs:
            server: 10.128.0.54
            path: /log
        - name: conf
          configMap:
            name: was-conf
