apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrinder-agent
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ngrinder-agent
  template:
    metadata:
      labels:
        app: ngrinder-agent
    spec:
      containers:
      - name: ngrinder-agent
        image: ngrinder/agent:3.5.4
        args: [ngrinder-svc:80]
